import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {parse} from 'acorn';
const code=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const ast=parse(code,{ecmaVersion:'latest',sourceType:'module'});
const decl=ast.body.find(n=>n.type==='VariableDeclaration'&&n.declarations.some(d=>d.id.name==='trainIt'));
const ctx={TRAIN_POS:[0,0],M:{data:{quizDone:false}},BP_STATE:{cooldownUntil:0},performance:{now:()=>100},player:{registered:false},toast(){},runQuiz(cb){ctx.quizCount++;cb();},runBP(cb){ctx.healthCount++;ctx.healthCallback=cb;},quizCount:0,healthCount:0};
vm.createContext(ctx);vm.runInContext(code.slice(decl.start,decl.end)+';globalThis.training=trainIt;',ctx);
ctx.training.action();assert.equal(ctx.quizCount,1);assert.equal(ctx.healthCount,1);assert.equal(ctx.player.registered,false);
ctx.healthCallback(false);assert.equal(ctx.player.registered,false);
ctx.BP_STATE.cooldownUntil=200;ctx.training.action();assert.equal(ctx.healthCount,1);
ctx.BP_STATE.cooldownUntil=0;ctx.training.action();assert.equal(ctx.quizCount,1);assert.equal(ctx.healthCount,2);
ctx.healthCallback(true);assert.equal(ctx.player.registered,true);
const gateCode=code.slice(code.indexOf('// Gate inspection uses the same admission state'));
const ui={};const gate={interactables:[],GATE:[0,0],GATE_OUT:0,inductionMode:null,$:id=>ui[id]||=( {style:{}} ),M:{data:{quizDone:false}},player:{registered:false,ppe:false},setGateOpen(open){gate.open=open;},toast(){}};
vm.createContext(gate);vm.runInContext(gateCode,gate);
gate.interactables[0].action();assert.equal(ui.gateScan.disabled,true);ui.gateScan.onclick();assert(!gate.player.admitted);
gate.M.data.quizDone=true;gate.player.registered=true;gate.player.ppe=true;gate.interactables[0].action();assert.equal(ui.gateScan.disabled,false);ui.gateScan.onclick();assert.equal(gate.player.admitted,true);assert.equal(gate.open,true);
console.log('PASS actual source callbacks: quiz -> health; failed health stays blocked; cooldown; retry avoids repeated quiz; gate requires training+health+PPE; accepted scan admits. Logic checks only, not browser completion.');
